### ISSUE TITLE
Research: Error handling imports in tests

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#105]
This issue has been created to reflect the problems we have encountered when attempting to run the tests.

## Motive for this issue:
When attempting to run the tests, the following error was encountered by @UO281801:
![image](https://user-images.githubusercontent.com/60737771/230084380-3a775fff-0ab6-4316-b2ad-c9cfaa1959f4.png)
The BaseVector.js was not created by any of the members of the project, and we believe the error is caused due to Jest not supporting the ES6 syntax used for imports in JavaScript

## Solving the issue:
Both @UO281801 and @PabVF23 studied the problem and attempted to solve it until it was decided it required further investigation.
If the problem is caused by compatibility issues, it is possible that some of the libraries used might need to be replaced. However, it is also possible that this could lead to further problems in the future.
Thus, collaborative research is needed to find the simplest and easiest to implement solution possible.

**Comment by pglez82** [comment]
In which branch is the code needed to reproduce the issue?

**Comment by UO281801** [comment]
In the UI branch, the error only happens when running "App.test.tsx" and "Sidebar.test.tsx"

**Comment by pglez82** [comment]
By default, the transformation of typescript files does not happen inside the node_modules directory. You are using components from a library (ol) that is inside node_modules and  need to be translated as they use typescript. You can modify you test launch scripts as follows, indicating that files under node_modules/ol, should be transfomed:

```json
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!ol)/\" --coverage",
```
This will get rid of the issue (the tests still won't work as they have other issues).

**Comment by UO281801** [comment]
Yes, this fixes this issue. Thanks!
