### ISSUE TITLE
Domain folder is duplicated in some branches

### ISSUE THREAD

**Issue by alvaroglezeri** [Arquisoft/lomap_en1a#107]
In some branches, there is a 'domain' folder in the project root and in the webapp/src folder as well. This is minor, and can be leaved as-is, but it might be better to remove one of them to avoid version conflict.

**Comment by alvaroglezeri** [comment]
In @RubendelRey's latest branch, this two folders contain conflicting information. This might have to be revised now 🤕

**Comment by PabVF23** [comment]
Due to issues with docker, there must be more than one domain folder, so this is no longer a problem.
