### ISSUE TITLE
Adapt the rest api in order to use pods.

### ISSUE THREAD

**Issue by RubendelRey** [Arquisoft/lomap_en1a#109]
In order to change the implementation of the rest api in order to use pods, there have been some changes:

### Visibility
PlaceVisibility has been replaced with Visibility, and there are three types:

- Public visibility: Any user can see a place or review with this visibility
- Friends visibility: Only users who are friends with the author of the place or review can see it.
- Private visibility: Only the author of the place or review can see it.

### Reviews (comments, scores and pictures)
Now reviews can have a visibility, and instead of being connected to the author with the User entity, they are connected through the web id of the author.

### Places
As well as in the reviews, places are not connected to their author by the User entity but by the web id of the author.

### User
Now the user entity does not extend the base entity, since users do not have an id. The purpose of the user entity is just to encapsulate the username and the web id of an user.

### Dtos
Dtos have been adapted to the changes explained above

## Controllers
Now controllers have been separated into 5 diferent files whose endpoints are:

#### List all comments for a given place
The endpoint for listing all the comments of a given place is /api/comment/list/:place.
For this endpoint the id of a place must be received, and it returns the list of comments for that given place.

#### Add a new comment
The endpoint for adding a comment is /api/comment/add.
For this endpoint a text, the id of the place and a visibility must be provided, in the body of the request, and it returns a boolean (true if the comment was added successfully or false if it was not)

#### List all scores for a given place
The endpoint for listing all the scores of a given place is /api/score/list/:place.
For this endpoint the id of a place must be received, and it returns the list of scores for that given place.

#### Add a new score
The endpoint for adding a score is /api/score/add.
For this endpoint a score, the id of the place and a visibility must be provided, in the body of the request, and it returns a boolean (true if the score was added successfully or false if it was not).

#### List all pictures for a given place
The endpoint for listing all the pictures of a given place is /api/picture/list/:place.
For this endpoint the id of a place must be received, and it returns the list of pictures for that given place.

#### Add a new picture
The endpoint for adding a picture is /api/picture/add.
For this endpoint a url of the image, the id of the place and a visibility must be provided, in the body of the request, and it returns a boolean (true if the picture was added successfully or false if it was not).

#### List all public places
The endpoint for listing public places is /api/place/public/list.
The endpoint returns all the public places in the application.

#### List all places shared with friends created by the given user.
The endpoint for listing places shared with friends is /api/friends/friends/list/:user.
For this endpoint a user must be provided, and it returns the places created by that user that they shared with their friends.

#### List all private places created by the logged user
The endpoint for listing private places is /api/place/private/list.
The endpoint returns all private places created by the logged user.

#### List all places shared with the logged user
The endpoint for listing shared places is /api/place/shared/list.
The endpoint returns shared places with the user, by their friends.

#### Add a new place
The endpoint for adding a place is /api/place/add.
For this endpoint a name, a description, a latitude, a longitude and a visibility must be provided, in the body of the request, and it returns the id of the added place.

#### Log In
The endpoint for logging in into the application is /api/login/:provider/:redirect.
For this endpoint, a pod provider url and a redirect url must be provided.

#### Log out
The endpoint for logging out of the application is /api/logout.
If the user has logged out successfully, the endpoint returns the message "Logged out".

#### Get the profile
There are two endpoints: /api/profile and /api/profile/:webId
The first endpoint returns the profile of the logged user, and the second, given the webId of a user, returns their profile.

#### Get friends
The endpoint for getting the friends of a given web id.

* Important note: All urls given to any get endpoint MUST BE encoded with javascripts function encodeURIComponent(string)

Service layer and repositories layer have been adapted to the new rest api requirements, and new classes have been added in order to deal with the interaction of pods.

**Comment by PabVF23** [comment]
I have implemented a basic version of the login that seems to work fine, but when i redirect to the webapp and fetch data from it, the session seems to restore itself.
I need some help to solve this problem.

**Comment by UO281801** [comment]
Everything works with pods except the logout and showing the information of the logged user in the menu

**Comment by Diego-274** [comment]
Does this issue still need to be open?

**Comment by PabVF23** [comment]
I am going to close this issue, as I think no more adaptations are needed. Feel free to open this issue again if you notice anything more is needed.
