### ISSUE TITLE
Fill "3. System Scope and Context" of the documentation

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#11]
* Link to main issue: #8
# List of parts of the section:
## 3.1. Business Context
This section has been assigned to Álvaro González Erigoyen
### Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners (neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

### Motivation
The domain interfaces and technical interfaces to communication partners are among your system’s most critical aspects. Make sure that you completely understand them.

### Form
Various options:

- Context diagrams
- Lists of communication partners and their interfaces.

## 3.2. Technical Context
This section has been assigned to Pablo Valdés Fernández
### Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

### Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

### Form
E.g. UML deployment diagram describing channels to neighboring systems, together with a mapping table showing the relationships between channels and input/output.

**Comment by alvaroglezeri** [comment]
The first image must be color-inverted. Black background should be changed.
