### ISSUE TITLE
Self-report 3: Sergio del Rey Álvarez

### ISSUE THREAD

**Issue by UO282497** [Arquisoft/lomap_en1a#121]
# Report
For this second part of the development, I moved my focus from restapi to webapp, since there were many fixes to do. One of the reasons was that the majority of the issues made were related to webapp, and I saw the opportunity to contribute to the team in that way. Then, the other reason was that my mates @RubendelRey and @alvaroglezeri were in an early (but steady) design phase of the pods integration into the application. Being more concrete, my work was based on the friends integration and fixing login and beautifying some parts of the app.
I think the team performed really well this phase since, the most difficult part (joining both restapi and webapp), was done in calls, the work done was very efficient, and the team dynamics were splendid.

# Issues
* #78 
* #93 
* #80 
* #95 
* #103 
* #94 
* #84

**Comment by UO281801** [comment]
Agree

**Comment by RubendelRey** [comment]
Agree

**Comment by alvaroglezeri** [comment]
Agree

**Comment by Diego-274** [comment]
Agree

**Comment by PabVF23** [comment]
:thumbsup:
