### ISSUE TITLE
Improve general usability

### ISSUE THREAD

**Issue by alvaroglezeri** [Arquisoft/lomap_en1a#126]
# Issue description:
The application's usability is lower than expected. It should be improved so even naive users will not struggle with understanding it.
## Improvement ideas:
* Include icons to reflect loading status of markers, friends, reviews, etc.
* Improve navegability of the application.
* Texts must be reviewed so component purposes can be instantly understood.
* Test with real-world users to discover unexpected friction points.
* Add a legend to the map for the user to know what visibility level is associated to each marker color
## Subissues:
* #134 
### Important comment
Any new information or improvement related to this issue should be reflected in a comment for all assignees to see

**Comment by UO282497** [comment]
Processes which load time needs to be issued:

- Markers (in the map view)
- Markers (in the slide bar)
- Friends (in the slide bar)
- Friend shared sites (in the friend profile panel)
- Adding a marker
- Load image of a marker
- Load comments and rating of a place
- Filtering places
- Load profile (from "My Profile" view)
- Add images to a marker
- Add comments to a marker
- Rate (with starts) a marker

**Comment by UO282497** [comment]
All the needed processes have loading screen, and malicious interactions when loading are properly handled
