### ISSUE TITLE
Replace placeholders

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#127]
# Issue description:
There is some stuff in the application that is supposed to be a placeholder. It must be either replaced by a final, customized version for the final delivery, or be removed altogether if it is no longer necessary.
## Examples:
 * Images in home page
 * Icon in navbar
 * App window logo
 * Profile and friend image
 * Profile and FAQ items in map side bar
 * Sign up link in navbar (this one should be removed)

**Comment by Diego-274** [comment]
The only remaining point is the Profile and friend image. All other placeholders have been removed.

**Comment by Diego-274** [comment]
Done
