### ISSUE TITLE
Add place category

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#135]
# Issue description:
The place categories are not currently implemented. They must be added for the final delivery.

## Subsections:
 * Add category to place, as well as option to add it on creation.
 * Add options to filter by category.

**Comment by UO281801** [comment]
I added the categories in the create place window

**Comment by PabVF23** [comment]
I have implemented a component to filter by category, but the category must be passed to the marker upon creation to finish implementing the filters
