### ISSUE TITLE
Add visibility to comments

### ISSUE THREAD

**Issue by vanesaalonso** [Arquisoft/lomap_en1a#138]
When creating a comment, the user should be able to choose a visibility

**Comment by UO281801** [comment]
Finished in the WebApp, but there is a bug in the RestApi, in the comment controller:
"<Visibility>req.params.visibility;" instead of "<Visibility>req.body.visibility;". The same bug appears in the Scores controller @RubendelRey check this bug for me please

**Comment by UO281801** [comment]
This is finished
