### ISSUE TITLE
Fill "6. Runtime View" of the documentation

### ISSUE THREAD

**Issue by Diego-274** [Arquisoft/lomap_en1a#14]
* Link to the main issue #8
# List of parts of the section:
### Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

- Important use cases or features: how do building blocks execute them?
- Interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
- Operation and administration: launch, start-up, stop
- Error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their architectural relevance. It is not important to describe a large number of scenarios. You should rather document a representative selection.

### Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime. You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

### Form
There are many notations for describing scenarios, e.g.
- Numbered list of steps (in natural language)
- Activity diagrams or flow charts
- Sequence diagrams
- BPMN or EPCs (event process chains)
- State machines

**Comment by PabVF23** [comment]
== Current status:
* Added login runtime scenario using PlantUML
* Added location addition runtime scenario using PlantUML

== To do:
* Location review runtime scenario pending to be added
* Send location addition scenario to workmates for peer review

**Comment by PabVF23** [comment]
##Current status:
* Added location review runtime scenario using PlantUML
##To do;
* Send scenarios to workmates for peer review
* Do pull request

**Comment by PabVF23** [comment]
## Current status:
* Finished
