### ISSUE TITLE
Self-report 1: Álvaro González Erigoyen

### ISSUE THREAD

**Issue by alvaroglezeri** [Arquisoft/lomap_en1a#45]
# Report
For this deliverable I have done sections 5 and 3's first half of the documentation. This is, the building block view and the system scope and context. For me, the biggest inconvenience has been the lack of an implementation, as my assigned sections greatly depend on the actual code of the system. For the next deliverable, I strive to complete said sections, and fill out the Glossary with the required terms and definitions. Also, I will try to have everything ready as soon as possible, so to not overwhelm myself and others with extra work at the end of the work-assigned term.

# Issues
* [System Scope and Context](https://github.com/Arquisoft/lomap_en1a/issues/11) 
* [Building Block View](https://github.com/Arquisoft/lomap_en1a/issues/13) 
* [Glossary](https://github.com/Arquisoft/lomap_en1a/issues/19)

**Comment by UO281801** [comment]
Agree

**Comment by Diego-274** [comment]
Agree

**Comment by RubendelRey** [comment]
Agree

**Comment by PabVF23** [comment]
Agree

**Comment by UO282497** [comment]
Agree
