### ISSUE TITLE
Self-report 2: Álvaro González Erigoyen

### ISSUE THREAD

**Issue by alvaroglezeri** [Arquisoft/lomap_en1a#71]
# Report
For this deliverable I have focused on figuring out POD access. Several libraries were tested (@inrupt/solid-client, @inrupt/solid-client-authn-browser, @inrupt/solid-client-authn-node, solid-node-client, solid-auth-fetcher), and their functioning was analyzed. There is still a lot of work to do to get the POD API to work correctly, but there is a big progress. 

## Issues
* #52

**Comment by Diego-274** [comment]
Agree

**Comment by UO281801** [comment]
Agree

**Comment by PabVF23** [comment]
Agree

**Comment by UO282497** [comment]
Agree

**Comment by RubendelRey** [comment]
Agree
