### ISSUE TITLE
Research: Handling asynchronous data.

### ISSUE THREAD

**Issue by UO282497** [Arquisoft/lomap_en1a#79]
This issue reflects the research done by @UO282497 regarding the way of handling persistence asynchronously. 
# Origin of the issue
For persisting data, a MySql database was chosen. Working with the library at first seemed easy. I made a general utility class using a singleton pattern, which made interaction with the database easier. But, when testing came, some observations were remarkable.
* Results from querying were not updated simulating a synchronous execution (marking the function as async and calling it with await).
* Not even errors where displaying correctly after calling to a query and getting the result.
# Attempting to get a solution
At first I thought that maybe there was a bug, or async/await wasn't working as I expected, so I did what it looked like the easier way to debug, introducing timeouts to the synchronous code. But, I found quite difficult and inefficient in Typescript to implement such mechanism, which was just for testing.
# Understanding the solution
After some research, and lots of testing I arrived at the following conclusion. To make it easy to understand, I will base it on this example.
![image](https://user-images.githubusercontent.com/113892055/224684990-62f3ccda-5216-4f53-ab44-2d947c80fb63.png)
In this function, the already created connection is being used to query the database, and in the same function, not executing what to do, but assigning to the MySql controller the function to execute when it decides that the query should be executed.
From this we can deduce that there is not an implicit call to the handler function in my code (only the definition). So this brings us to the problem:
* So we know that we need the handler function to be executed simulating sinchronously, but, we aren't in control of the explicit call to it.
* By tagging the get function (shown above), it only wait for the code to ASSIGN the handler to the query, not to EXECUTE it.
# Current solution
The only way I found of ensuring that code related to managing extracted data, is executed only when the extraction is done successfully, is by doing promises with the data, which made an issue which affected all of my teammates.
# The issue of using Promises
Since this research involved a lot of my time, the solution involved changing a lot of my colleagues code, since data handling became more verbose and any return involving this data, had to be encapsulated into a new promise, and the promise accessing processs was delegated to the next layer.
![image](https://user-images.githubusercontent.com/113892055/224688446-1fd9bc67-3e83-4dbb-8d36-e8b25fdee6eb.png)
Here is how I'm currently accessing the place/s which have a specific ID.
![image](https://user-images.githubusercontent.com/113892055/224689363-4fc81f9c-0ffe-4a32-b14e-3cd945c2da04.png)
Here is the part of the logic, which delegates the promise to the controller.
![image](https://user-images.githubusercontent.com/113892055/224689570-ef73aa2f-cee1-4bcf-a667-5bcefac39724.png)
And here is the code of the controller, which also delegates the promise to the next layer.
![image](https://user-images.githubusercontent.com/113892055/224691462-607f4165-e8e2-4645-ad09-6760624b4223.png)
And here is the code of a component which also needs a 'then()' to acces the information.

**Comment by alvaroglezeri** [comment]
Has this issue been solved? @UO282497
