### ISSUE TITLE
Fill the project's documentation

### ISSUE THREAD

**Issue by UO282497** [Arquisoft/lomap_en1a#8]
# Sub-issues:
* #9 
* #10 
* #11 
* #12
* #13
* #14 
* #16 
* #15
* #17
* #20 
* #18 
* #19

**Comment by alvaroglezeri** [comment]
Link para editar archivos .adoc:
https://powerman.name/doc/asciidoc

**Comment by alvaroglezeri** [comment]
The final version of the Documentation is now implemented. There might be still some small errors in it, but if they are, they most likely are minor.
