### ISSUE TITLE
Self Report 2: Sergio del Rey Álvarez

### ISSUE THREAD

**Issue by UO282497** [Arquisoft/lomap_en1a#81]
# Work done
For the prototype, I was encharged of persisting data, concretely in the database. Since we were already familiarized with querying databases, I decided to create a full database, since my colleague @alvaroglezeri had quite a heavy load of work researching about accessing and storing data in pods. So at first the majority of our data was stored int the database. 
Being more concrete I was in charge of making the communication with the database and creating a way of communicating the results (in this case a repository per table).
# Insights
Apart from having to implement the code, I had to research about asynchronous retrieval of data using the MySQL library (documented in #79).
# Issues
#53 
#52

**Comment by alvaroglezeri** [comment]
Agree!

**Comment by PabVF23** [comment]
Agree

**Comment by Diego-274** [comment]
Agree

**Comment by RubendelRey** [comment]
Agree
