### ISSUE TITLE
Fix marker deletion when not adding a place

### ISSUE THREAD

**Issue by Diego-274** [Arquisoft/lomap_en1a#89]
A marker is placed even if a place isn't created in the database.

**Comment by UO281801** [comment]
I have fixed this partially: the component knows when it has to delete the marker already, but for some reason it does not delete it (at least visually) from the map. It is probably an error in vector.tsx, but I do not see it. Could you check it @PabVF23 and @Diego-274? It is already in the UI branch

**Comment by PabVF23** [comment]
No problem, I will gladly help you.

**Comment by UO281801** [comment]
Fixed
