### ISSUE TITLE
Fill "1. Introduction and Goals" of the documentation

### ISSUE THREAD

**Issue by UO282497** [Arquisoft/lomap_en1a#9]
* Link to main issue: #8
# List of parts of the section:

## 1.1. Requirements overview
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include:
- underlying business goals, essential features and functional requirements for the system
- quality goals for the architecture
- relevant stakeholders and their expectations

### Contents
Short description of the functional requirements, driving forces, extract (or abstract) of requirements. Link to (hopefully existing) requirements documents (with version number and information where to find it).

### Motivation
From the point of view of the end users a system is created or modified to improve support of a business activity and/or improve the quality.

### Form
Short textual description, probably in tabular use-case format. If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.

### Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that:
- should know the architecture
- have to be convinced of the architecture
-  have to work with the architecture or with code
- need the documentation of the architecture for their work
-  have to come up with decisions about the system or its development

### Motivation
You should know all parties involved in development of the system or affected by the system. Otherwise, you may get nasty surprises later in the development process. These stakeholders determine the extent and the level of detail of your work and its results.

### Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.

**Comment by Diego-274** [comment]
[Main issue](https://github.com/Arquisoft/lomap_en1a/issues/8)
Solution Strategy
