### ISSUE TITLE
Migrate private user data from database to PODs

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#91]
The private user data should be moved to the PODs, leaving only public information in the database.

**Comment by alvaroglezeri** [comment]
In branch (persistence-alvaro)[https://github.com/Arquisoft/lomap_en1a/tree/persistence-alvaro], there has been implemented a functional fetch to POD resources. 

Current implementation allows logging in, logging out, and fetching private resources from a POD when logged in.
Known bugs are a few, among: 
* One user can log in several times. This will most likely be prevented in the UI by hiding the login button when logged in, but this should not be allowed.
* Trying to fetch user's A private file by user B does not get the contents, although user A has given access to user B.
