### ISSUE TITLE
Beautify login and logout

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#94]
## Description:
The login view and logout button should be made to be better looking, as the way they currently look is rather uncomfortable from a user perspective.
## Subsections:
 * The login webpage looks rather ugly, it should be more pleasant for the user to look at.
 * The logout button looks quite jarring, it should be replaced by a link similar to the one used to access the map.

**Comment by UO282497** [comment]
The log out was fixed easily by refactoring some css rules and making the element follow the rules of the list.

**Comment by Diego-274** [comment]
Finished.
