### ISSUE TITLE
Center map on relevant positions

### ISSUE THREAD

**Issue by PabVF23** [Arquisoft/lomap_en1a#96]
## Description:
There are certain conditions in which the map should be centered on certain positions to contribute to the overall user experience.
## Subsections:
 * When the user opens the map view from a different one, the map should be centered on the user's location, ideally with the highest precision possible.
 * When the user adds a new marker, the map should be centered on it.

**Comment by UO281801** [comment]
Now the map centers on the EII. Using the geolocation causes some problems

**Comment by UO281801** [comment]
Centering the map when the user adds a marker (changing the current center of the map) causes it to re-render completely. It is not a good idea. I think we should close this issue for now
